# Generated by Django 6.0 on 2026-10-01 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('bd_models', '0019_guildconfig_tips_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='currency_reward',
        ),
        migrations.CreateModel(
            name='AchievementReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('currency', 'Currency'), ('ball', 'Ball')], max_length=20)),
                ('currency_amount', models.PositiveIntegerField(default=0)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='achievements.achievement')),
                ('ball', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievement_rewards', to='bd_models.ball')),
            ],
        ),
    ]
