# Generated by Django 6.0 on 2026-10-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_remove_achievement_currency_reward_achievementreward'),
        ('bd_models', '0019_guildconfig_tips_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='required_balls',
            field=models.ManyToManyField(blank=True, related_name='required_for_achievements', to='bd_models.ball'),
        ),
    ]
