# Generated by Django 6.0 on 2026-10-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_achievement_required_balls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievementreward',
            old_name='amount',
            new_name='ball_amount',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='requirement_type',
            field=models.CharField(default='manual', max_length=50),
        ),
        migrations.AlterField(
            model_name='achievementreward',
            name='reward_type',
            field=models.CharField(choices=[('currency', 'Currency'), ('ball', 'Ball'), ('both', 'Currency + Ball')], default='currency', max_length=20),
        ),
    ]
