# Generated by Django 6.0 on 2026-10-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_rename_amount_achievementreward_ball_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='requirement_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('catch_balls', 'Catch balls'), ('specific_balls', 'Catch specific balls'), ('unique_balls', 'Catch unique balls'), ('catch_special', 'Catch special')], default='manual', max_length=50),
        ),
    ]
