# Generated by Django 6.0 on 2026-10-01 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0005_alter_achievement_requirement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='achievements.achievement')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('achievement', 'discord_id'), name='unique_achievement_completion')],
            },
        ),
    ]
